### ISSUE TITLE
v144 crash

### ISSUE THREAD

**Issue by JiroCab** [xzxADIxzx/Scheme-Size-Lite#1]
aka conflict with the new join dialog 

[crash-report-05_12_2023_20_53_51.txt](https://github.com/xzxADIxzx/Scheme-Size-Lite/files/11464087/crash-report-05_12_2023_20_53_51.txt)

cheers & hope it helps <3

**Comment by xzxADIxzx** [comment]
Please update the mod: I fixed this bug in the last update.
And thanks for the provided log :3
