### ISSUE TITLE
Scheme size lite do not work on 146 build on android

### ISSUE THREAD

**Issue by Noname0fm1nemas** [xzxADIxzx/Scheme-Size-Lite#2]
when I imported the mod it did not have a picture, and there is no “ClaJ” button in the network game tab

**Comment by xzxADIxzx** [comment]
Uh

**Comment by xzxADIxzx** [comment]
Well... I've tested it and I have no idea why it doesn't work ;-;

**Comment by xzxADIxzx** [comment]
Omg, are you kidding me?!
An error occurred during compilation, but GitHub Actions not only did not report it, but also wrote that everything was successful!

**Comment by Noname0fm1nemas** [comment]
that is, it didn’t work because of Github?

**Comment by Noname0fm1nemas** [comment]
> Omg, are you kidding me?!
> An error occurred during compilation, but GitHub Actions not only did not report it, but also wrote that everything was successful!

that is, it didn’t work because of Github?

**Comment by Noname0fm1nemas** [comment]
> > Omg, are you kidding me?!
> > An error occurred during compilation, but GitHub Actions not only did not report it, but also wrote that everything was successful!
> 
> that is, it didn’t work because of Github?

I just don’t understand mindustry mods, and I write mods for minecraft

**Comment by xzxADIxzx** [comment]
Sometimes I don't understand them too

**Comment by Noname0fm1nemas** [comment]
> Sometimes I don't understand them too

have you already fixed it?

**Comment by xzxADIxzx** [comment]
Fixed, sorry for the issue
